### PR TITLE
[feat] Create Home Page

### PR DESCRIPTION
**Pull request by Hamdrive**
Created Home page of FueledUp™ E-commerce store. Majority of styling was used from PowerTrainUI™ library

Features:
1. Nav and footer (responsive)
2. A landing hero image
3. Categories
4. Collections

### CODE REVIEW

**Review by AnuragSahu11 — COMMENTED** [review]
Everything looks good just a suggestion you could add cursor: pointer to categories section.

**Review by shivampandey0 — COMMENTED** [review]
looks good to merge.
Images take a long time to load.

**Review by abhij1607 — APPROVED** [review]
Nice work, good practices followed

**Comment by Hamdrive** [comment]
Comments noted, will implement changes to image lateron in production.
Merging to dev

**Pull request merged**
