### PR TITLE
[chore] Issue #20 : Update links to all pages

### LINKED ISSUE #20: Link to other pages missing (buttons, texts, icons)
Noticed that some elements which are supposed to redirect to other pages seem to be missing their URL inside the `href` attribute.

Chore:
1. Check and ensure links are present wherever needed

### PR DESCRIPTION
**Pull request by Hamdrive**
Refer issue #20 

Noticed that some elements which are supposed to redirect to other pages seem to be missing their URL inside the href attribute.

Chore:
1. Check and ensure links are present wherever needed

### CODE REVIEW

**Review by hinanshisuthar — COMMENTED** [review]
I hope the links are working now. In the preview If i click on sign-up its taking me no where. Is this what suppose to happen? Because here it seems you have linked the pages.

**Review by ZuberDunge — APPROVED** [review]
All links are working fine. also, UI looks good.

**Comment by Hamdrive** [comment]
> I hope the links are working now. In the preview If i click on sign-up its taking me no where. Is this what suppose to happen? Because here it seems you have linked the pages.

Hey @hinanshisuthar , you are right I had not implemented the anchor tag for icons correctly, have rectified the same and has also been approved by @ZuberDunge .

**Comment by Hamdrive** [comment]
Issue has been rectified and cleared by reviewers, this fixes #20 and will merge to dev and close this branch

**Pull request merged**
