### PR TITLE
[refactor] Issue #17 : Spacing/Margins/Padding of all webpages

### LINKED ISSUE #17: Inconsistent spacing/padding/margin in website
I have noticed parts of the website wherein there is inconsistencies in the spacing/padding/margin in components of the site.

Chore:
1. Check spacing/padding/margin for all components
2. Check spacing/padding/margin for all webpages

### PR DESCRIPTION
**Pull request by Hamdrive**
Refer issue #17 

Just UI changes made, hence would suggest to visit the website [here](https://deploy-preview-21--fueledup.netlify.app/) and check the overall spacing on all pages.

I have noticed parts of the website wherein there is inconsistencies in the spacing/padding/margin in components of the site.
Hence sucessfully refactored necessary components and pages to ensure good spacing given, as well as minimal to none breaking of component or webpage on small/large screens.

Chore:

1. Check spacing/padding/margin for all components
2. Check spacing/padding/margin for all webpages

### CODE REVIEW

**Review by shivampandey0 — COMMENTED** [review]
Looks good with consistent margins and padding

**Review by hinanshisuthar — COMMENTED** [review]
Good how you used variables wherever possible. Is there any specific reason for choosing px over rems in width? Everything else looks good to merge.

**Comment by Hamdrive** [comment]
> Good how you used variables wherever possible. Is there any specific reason for choosing px over rems in width? Everything else looks good to merge.

Good catch, I was testing out sizes which ideally would not break, and did not update it to rems and follow my usual coding architecture. Changed it in the most recent commit!

**Comment by Hamdrive** [comment]
Issue has been reviewed and successfully passes all checks. This fixes #17 and will be merged and closed.

**Pull request merged**
