### PR TITLE
Issue #5 : [refactor][fix] Create new CSS file for common classes

### LINKED ISSUE #5: Common stylings in one css file
As I have overridden the CSS utility class being imported from PowertrainUI™, I would like to create a common CSS file wherein all those overriding classes are stored, thus easily accessible and can be applied across all pages easily without repetition of code.

### PR DESCRIPTION
**Pull request by Hamdrive**
Created a new CSS common file referring to issue #5 
Successfully implemented changes and code/project still working as expected

### CODE REVIEW

**Review by RakshithBhat03 — APPROVED** [review]
The code looks clean and well structured. Good use of variables as well. Good to merge

**Comment by saadahmadhere** [comment]
Looks good to me.

**Review by saadahmadhere — COMMENTED** [review]
Looks good.

**Comment by Hamdrive** [comment]
This fixes #5, closing and merging to dev

**Pull request merged**
